# Generated by Django 4.0 on 2021-12-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile',
            field=models.ImageField(default='img/cage.jpg', upload_to='img/profiles/%Y/%m/%d/'),
        ),
    ]
