# Generated by Django 4.0 on 2021-12-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_account_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec iaculis mauris.', max_length=200),
        ),
    ]
