name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pwd
        source envs/pyinsta/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd pyinsta
        python manage.py test
    
#CAIO ESSA PARTE VC CONFIGURA PRO SEU SERVIDOR    
#    - name: ssh-scp-ssh-pipelines
#      # You may pin to the exact commit or the version.
#      # uses: cross-the-world/ssh-scp-ssh-pipelines@78e864b4890087a58248ff39320406971ca88b89
#      uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
#      with:
#        # ssh remote host
#        host: 
#        # ssh remote port
#        port: # optional, default is 22
#        # ssh remote user
#        user: 
#        # content of ssh private key. ex raw content of ~/.ssh/id_rsa
#        key: # optional
#        # ssh remote password
#        pass: # optional
#        # connection timeout to remote host
#        connect_timeout: # optional, default is 30s
#        # execute pre-commands before scp
#        first_ssh: # optional
#        # scp from local to remote
#        scp: # optional
#        # execute post-commands after scp
#        last_ssh: # optional
